-- FitHub 1.3.0 update
-- Gym-session invites, optional workout-post photos and richer feed data.
-- Run once in Supabase Dashboard -> SQL Editor.

alter table public.workout_posts add column if not exists caption text;
alter table public.workout_posts add column if not exists photo_path text;

create table if not exists public.gym_invites (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.public_profiles(user_id) on delete cascade,
  recipient_id uuid not null references public.public_profiles(user_id) on delete cascade,
  session_at timestamptz not null,
  gym_name text,
  workout_name text,
  note text,
  status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create index if not exists gym_invites_sender_time_idx on public.gym_invites(sender_id, session_at desc);
create index if not exists gym_invites_recipient_time_idx on public.gym_invites(recipient_id, session_at desc);

alter table public.gym_invites enable row level security;
drop policy if exists "gym invites involved read" on public.gym_invites;
drop policy if exists "gym invites sender insert" on public.gym_invites;
drop policy if exists "gym invites involved update" on public.gym_invites;
drop policy if exists "gym invites sender delete" on public.gym_invites;
create policy "gym invites involved read" on public.gym_invites
  for select to authenticated
  using (sender_id = auth.uid() or recipient_id = auth.uid());
create policy "gym invites sender insert" on public.gym_invites
  for insert to authenticated
  with check (
    sender_id = auth.uid()
    and recipient_id <> auth.uid()
    and public.are_friends(auth.uid(), recipient_id)
  );
create policy "gym invites involved update" on public.gym_invites
  for update to authenticated
  using (sender_id = auth.uid() or recipient_id = auth.uid())
  with check (sender_id = auth.uid() or recipient_id = auth.uid());
create policy "gym invites sender delete" on public.gym_invites
  for delete to authenticated
  using (sender_id = auth.uid());

-- Private workout photo bucket. The app generates short-lived signed URLs for feed display.
insert into storage.buckets(id,name,public)
values('workout-media','workout-media',false)
on conflict(id) do update set public=false;

drop policy if exists "workout media own read" on storage.objects;
drop policy if exists "workout media own insert" on storage.objects;
drop policy if exists "workout media own update" on storage.objects;
drop policy if exists "workout media own delete" on storage.objects;
create policy "workout media own read" on storage.objects for select to authenticated
  using(bucket_id='workout-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "workout media own insert" on storage.objects for insert to authenticated
  with check(bucket_id='workout-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "workout media own update" on storage.objects for update to authenticated
  using(bucket_id='workout-media' and (storage.foldername(name))[1]=auth.uid()::text)
  with check(bucket_id='workout-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "workout media own delete" on storage.objects for delete to authenticated
  using(bucket_id='workout-media' and (storage.foldername(name))[1]=auth.uid()::text);

-- Signed URLs are generated by an authenticated client. Friends can only discover
-- a photo path through this RPC when the post itself is visible to them.
create or replace function public.get_friend_feed_v3()
returns table(
  id uuid,
  user_id uuid,
  session_id uuid,
  username text,
  avatar_url text,
  summary text,
  caption text,
  photo_path text,
  created_at timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  exercise_count bigint,
  total_sets bigint,
  total_volume numeric,
  total_distance numeric,
  exercise_names text
)
language sql stable security definer set search_path = public as $$
  select
    wp.id, wp.user_id, wp.session_id, pp.username::text, pp.avatar_url,
    wp.summary, wp.caption, wp.photo_path, wp.created_at,
    ws.started_at, ws.ended_at,
    count(distinct wset.exercise_name),
    count(wset.id),
    coalesce(sum(coalesce(wset.weight_kg,0) * coalesce(wset.reps,0)),0),
    coalesce(sum(coalesce(wset.distance_km,0)),0),
    coalesce(string_agg(distinct wset.exercise_name, ', '),wp.summary)
  from public.workout_posts wp
  join public.public_profiles pp on pp.user_id=wp.user_id
  join public.workout_sessions ws on ws.id=wp.session_id
  left join public.workout_sets wset on wset.session_id=wp.session_id
  where wp.user_id=auth.uid() or public.are_friends(auth.uid(),wp.user_id)
  group by wp.id,wp.user_id,wp.session_id,pp.username,pp.avatar_url,wp.summary,wp.caption,wp.photo_path,wp.created_at,ws.started_at,ws.ended_at
  order by wp.created_at desc
  limit 60;
$$;
grant execute on function public.get_friend_feed_v3() to authenticated;

-- Allow friends who can see a workout post to download its private image.
-- We use a SECURITY DEFINER function to mint the path visibility; Storage itself
-- remains private and signed URLs are created client-side for the authenticated user.
-- Add a read policy for photo objects referenced by a visible post.
drop policy if exists "workout media visible post read" on storage.objects;
create policy "workout media visible post read" on storage.objects for select to authenticated
using (
  bucket_id='workout-media'
  and exists (
    select 1 from public.workout_posts p
    where p.photo_path = storage.objects.name
      and (p.user_id = auth.uid() or public.are_friends(auth.uid(), p.user_id))
  )
);

-- Realtime updates for gym invites.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='gym_invites'
  ) then
    alter publication supabase_realtime add table public.gym_invites;
  end if;
end $$;
