import React, { useEffect, useState } from 'react';
import { Alert, Image, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Button, Card, Chip, Input, SectionTitle, useTheme } from '../../components/UI';
import { cmFrom, kgFrom, maintenanceCalories, proteinTarget } from '../../lib/health';
import { Profile } from '../../lib/types';
import { supabase } from '../../lib/supabase';

export default function ProfileTab({ profile, onProfileChanged }: { profile: Profile; onProfileChanged: () => void }) {
  const { colors, themeMode, setThemeMode } = useTheme(); const styles = createStyles(colors);
  const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(false);
  const [age,setAge]=useState(''); const [fitness,setFitness]=useState('new'); const [activity,setActivity]=useState('light'); const [gender,setGender]=useState('prefer_not_to_say'); const [goal,setGoal]=useState('improve_fitness'); const [days,setDays]=useState('3');
  const [heightUnit,setHeightUnit]=useState<'cm'|'in'>('cm'); const [weightUnit,setWeightUnit]=useState<'kg'|'lb'>('kg'); const [height,setHeight]=useState(''); const [weight,setWeight]=useState('');

  useEffect(()=>{
    const hu=(profile.height_unit==='in'?'in':'cm') as 'cm'|'in'; const wu=(profile.weight_unit==='lb'?'lb':'kg') as 'kg'|'lb'; setHeightUnit(hu); setWeightUnit(wu);
    setAge(profile.age?String(profile.age):''); setFitness(profile.fitness_level??'new'); setActivity(profile.activity_level??'light'); setGender(profile.gender??'prefer_not_to_say'); setGoal(profile.goal??'improve_fitness'); setDays(String(profile.workout_days_target??3));
    setHeight(profile.height_cm?String(hu==='cm'?Math.round(profile.height_cm*10)/10:Math.round(profile.height_cm/2.54*10)/10):''); setWeight(profile.weight_kg?String(wu==='kg'?Math.round(profile.weight_kg*10)/10:Math.round(profile.weight_kg/0.45359237*10)/10):'');
  },[profile.id,profile.age,profile.weight_kg,profile.height_cm,profile.goal,profile.activity_level,profile.fitness_level,profile.gender,profile.workout_days_target,profile.height_unit,profile.weight_unit]);

  const uploadAvatar=async()=>{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.8});if(result.canceled)return;setBusy(true);try{const asset=result.assets[0];const bytes=await(await fetch(asset.uri)).arrayBuffer();const ext=(asset.fileName?.split('.').pop()||'jpg').toLowerCase();const path=`${profile.id}/avatar.${ext}`;const {error:up}=await supabase.storage.from('avatars').upload(path,bytes,{contentType:asset.mimeType??'image/jpeg',upsert:true});if(up)throw up;const {data}=supabase.storage.from('avatars').getPublicUrl(path);const {error}=await supabase.from('profiles').update({avatar_url:`${data.publicUrl}?v=${Date.now()}`}).eq('id',profile.id);if(error)throw error;onProfileChanged();}catch(e:any){Alert.alert('Profile photo',e?.message??'Upload failed.');}finally{setBusy(false);}};

  const saveDetails=async()=>{
    const a=Number(age),w=Number(weight),h=Number(height),d=Number(days); if(!a||a<13||a>100||!w||w<=0||!h||h<=0||!d||d<1||d>7)return Alert.alert('Check your details','Enter valid age, height, weight and training days.');
    const kg=kgFrom(w,weightUnit),cm=cmFrom(h,heightUnit),adult=a>=18; const payload:any={age:a,fitness_level:fitness,activity_level:activity,gender,goal,workout_days_target:d,height_cm:cm,weight_kg:kg,height_unit:heightUnit,weight_unit:weightUnit,maintenance_calories:adult?maintenanceCalories(a,kg,cm,gender,activity):null,protein_target_g:adult?proteinTarget(kg,goal):null};
    setBusy(true);let {error}=await supabase.from('profiles').update(payload).eq('id',profile.id);if(error&&/height_unit|weight_unit|column/i.test(error.message)){delete payload.height_unit;delete payload.weight_unit;({error}=await supabase.from('profiles').update(payload).eq('id',profile.id));}setBusy(false);if(error)return Alert.alert('Could not save',error.message);setEditing(false);onProfileChanged();
  };
  const signOut=async()=>{await supabase.auth.signOut();};

  return <ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled">
    <Text style={styles.title}>Your profile</Text>
    <Card><View style={styles.profileRow}>{profile.avatar_url?<Image source={{uri:profile.avatar_url}} style={styles.avatar}/>:<View style={[styles.avatar,styles.fallback]}><Text style={styles.initial}>{profile.username.slice(0,1).toUpperCase()}</Text></View>}<View style={{flex:1}}><Text style={styles.name}>@{profile.username}</Text><Text style={styles.meta}>{profile.email}</Text><Text style={styles.meta}>✦ {profile.tokens} tokens</Text></View></View><Button title={busy?'Uploading…':'Change profile picture'} onPress={uploadAvatar} disabled={busy} secondary/></Card>

    <Card><SectionTitle title="Appearance" subtitle="Choose how FitHub looks on this device."/><View style={styles.themeRow}><Chip label="System" active={themeMode==='system'} onPress={()=>setThemeMode('system')}/><Chip label="Dark" active={themeMode==='dark'} onPress={()=>setThemeMode('dark')}/><Chip label="Light" active={themeMode==='light'} onPress={()=>setThemeMode('light')}/></View></Card>

    <Card><View style={styles.cardTitleRow}><SectionTitle title="Personal & fitness details" subtitle="Change any answer from your original setup whenever you need to."/><Pressable onPress={()=>setEditing(!editing)}><Text style={styles.edit}>{editing?'Close':'Edit'}</Text></Pressable></View>
      {!editing?<><Info label="Age" value={profile.age?String(profile.age):'—'}/><Info label="Experience" value={profile.fitness_level?.replaceAll('_',' ')??'—'}/><Info label="Activity" value={profile.activity_level?.replaceAll('_',' ')??'—'}/><Info label="Goal" value={profile.goal?.replaceAll('_',' ')??'—'}/><Info label="Height" value={profile.height_cm?`${Math.round(profile.height_cm)} cm`:'—'}/><Info label="Weight" value={profile.weight_kg?`${profile.weight_kg.toFixed(1)} kg`:'—'}/><Info label="Training days" value={`${profile.workout_days_target} / week`}/><Info label="Adult maintenance estimate" value={(profile.age??0)>=18?`${profile.maintenance_calories??'—'} kcal/day`:'Not generated under age 18'}/><Info label="Adult protein target" value={(profile.age??0)>=18?`${profile.protein_target_g??'—'} g/day`:'Not generated under age 18'}/></>:<View>
        <Text style={styles.label}>Age</Text><Input value={age} onChangeText={setAge} keyboardType="number-pad" placeholder="Age"/>
        <Text style={styles.label}>Training experience</Text><View style={styles.wrapChips}>{[['new','Completely new'],['occasional','Occasional'],['regular','Regular']].map(([v,l])=><Chip key={v} label={l} active={fitness===v} onPress={()=>setFitness(v)}/>)}</View>
        <Text style={styles.label}>Activity outside workouts</Text><View style={styles.wrapChips}>{[['sedentary','Mostly seated'],['light','Light'],['moderate','Moderate'],['high','High']].map(([v,l])=><Chip key={v} label={l} active={activity===v} onPress={()=>setActivity(v)}/>)}</View>
        <Text style={styles.label}>Profile option</Text><View style={styles.wrapChips}>{[['female','Female'],['male','Male'],['prefer_not_to_say','Prefer not to say']].map(([v,l])=><Chip key={v} label={l} active={gender===v} onPress={()=>setGender(v)}/>)}</View>
        <Text style={styles.label}>Height</Text><View style={styles.inline}><Input style={{flex:1}} value={height} onChangeText={setHeight} keyboardType="decimal-pad" placeholder="Height"/><View style={styles.units}><Chip label="cm" active={heightUnit==='cm'} onPress={()=>setHeightUnit('cm')}/><Chip label="in" active={heightUnit==='in'} onPress={()=>setHeightUnit('in')}/></View></View>
        <Text style={styles.label}>Weight</Text><View style={styles.inline}><Input style={{flex:1}} value={weight} onChangeText={setWeight} keyboardType="decimal-pad" placeholder="Weight"/><View style={styles.units}><Chip label="kg" active={weightUnit==='kg'} onPress={()=>setWeightUnit('kg')}/><Chip label="lb" active={weightUnit==='lb'} onPress={()=>setWeightUnit('lb')}/></View></View>
        <Text style={styles.label}>Main goal</Text><View style={styles.wrapChips}>{[['gain_muscle','Gain muscle'],['fat_loss','Lose fat'],['maintain','Maintain'],['improve_fitness','Improve fitness']].map(([v,l])=><Chip key={v} label={l} active={goal===v} onPress={()=>setGoal(v)}/>)}</View>
        <Text style={styles.label}>Workout days per week</Text><Input value={days} onChangeText={setDays} keyboardType="number-pad" placeholder="1-7"/><Button title={busy?'Saving…':'Save changes'} onPress={saveDetails} disabled={busy}/>
      </View>}
    </Card>

    <Card><SectionTitle title="Evidence & safety" subtitle="FitHub uses estimates and training guidance, not medical diagnosis."/><Source title="CDC — Adult BMI calculator and BMI as a screening measure" url="https://www.cdc.gov/bmi/adult-calculator/index.html"/><Source title="NIDDK — Body Weight Planner (adult use)" url="https://www.niddk.nih.gov/health-information/weight-management/body-weight-planner"/><Source title="Mifflin–St Jeor resting energy equation — PubMed" url="https://pubmed.ncbi.nlm.nih.gov/2305711/"/><Source title="ACSM resistance-training guidance" url="https://acsm.org/"/><Source title="USDA FoodData Central API" url="https://fdc.nal.usda.gov/api-guide/"/></Card>
    <Button title="Sign out" onPress={signOut} secondary/>
  </ScrollView>;
}

function Info({label,value}:{label:string;value:string}){const {colors}=useTheme();const s=createStyles(colors);return <View style={s.info}><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value}</Text></View>;}
function Source({title,url}:{title:string;url:string}){const {colors}=useTheme();const s=createStyles(colors);return <Pressable onPress={()=>Linking.openURL(url)} style={s.source}><Text style={s.sourceText}>↗ {title}</Text></Pressable>;}
const createStyles=(colors:any)=>StyleSheet.create({wrap:{padding:16,paddingTop:10,paddingBottom:40},title:{color:colors.text,fontSize:29,fontWeight:'900',marginBottom:12},profileRow:{flexDirection:'row',gap:13,alignItems:'center',marginBottom:8},avatar:{width:74,height:74,borderRadius:37},fallback:{backgroundColor:colors.blueSoft,alignItems:'center',justifyContent:'center'},initial:{color:colors.text,fontSize:28,fontWeight:'900'},name:{color:colors.text,fontSize:21,fontWeight:'900'},meta:{color:colors.muted,fontSize:12,marginTop:3},themeRow:{flexDirection:'row',flexWrap:'wrap'},cardTitleRow:{flexDirection:'row',justifyContent:'space-between',gap:8},edit:{color:colors.blue,fontWeight:'900',fontSize:12,paddingTop:3},label:{color:colors.text,fontWeight:'900',fontSize:12,marginTop:8,marginBottom:7},wrapChips:{flexDirection:'row',flexWrap:'wrap'},inline:{flexDirection:'row',gap:8,alignItems:'flex-start'},units:{flexDirection:'row'},info:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},infoLabel:{color:colors.muted,flex:1},infoValue:{color:colors.text,fontWeight:'800',flex:1,textAlign:'right',textTransform:'capitalize'},source:{backgroundColor:colors.panel2,padding:10,borderRadius:12,marginTop:7},sourceText:{color:colors.blue,fontWeight:'800',lineHeight:18}});
