import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Input, OutlineButton, useTheme } from '../../components/UI';
import { Profile } from '../../lib/types';
import { supabase } from '../../lib/supabase';
import { progressionSuggestion } from '../../lib/progression';
import { recordWorkoutDay } from '../../lib/streaks';
import { exerciseLibrary, figureImages, LibraryExercise, muscleCards, muscleGroupFilters, summarizeTargets } from '../../data/exerciseLibrary';

type StrengthSet={id:string;weight:string;reps:string;done:boolean};
type BuilderItem={id:string;exercise:LibraryExercise;strengthSets:StrengthSet[];distance:string;duration:string;load:string;done:boolean;suggestion?:string};
type ScreenMode='browse'|'detail'|'active';
type DetailTab='sets'|'about';

const makeId=()=>`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const makeSets=(ex:LibraryExercise,count=3):StrengthSet[]=>Array.from({length:count},()=>({id:makeId(),weight:'',reps:String(ex.rep_max?Math.min(10,ex.rep_max):10),done:false}));
const makeItem=(ex:LibraryExercise):BuilderItem=>({id:`${ex.slug}-${makeId()}`,exercise:ex,strengthSets:ex.metric_type==='strength'?makeSets(ex):[],distance:'',duration:'',load:'',done:false});
const formatTime=(sec:number)=>`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;

export default function WorkoutTab({profile,onProfileChanged}:{profile:Profile;onProfileChanged:()=>void}){
  const {colors}=useTheme();const styles=createStyles(colors);
  const [screen,setScreen]=useState<ScreenMode>('browse');const [detailTab,setDetailTab]=useState<DetailTab>('sets');const [detailExercise,setDetailExercise]=useState<LibraryExercise|null>(null);const [query,setQuery]=useState('');const [muscleFilter,setMuscleFilter]=useState<(typeof muscleGroupFilters)[number]>('All');const [builder,setBuilder]=useState<BuilderItem[]>([]);const [lastWorkout,setLastWorkout]=useState<BuilderItem[]>([]);const [busy,setBusy]=useState(false);const [activeStartedAt,setActiveStartedAt]=useState<number|null>(null);const [elapsed,setElapsed]=useState(0);const [restSeconds,setRestSeconds]=useState(0);const [activeExerciseIndex,setActiveExerciseIndex]=useState(0);

  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return exerciseLibrary.filter(ex=>(muscleFilter==='All'||ex.targetArea===muscleFilter)&&(!q||`${ex.name} ${ex.targetArea} ${ex.subsection} ${ex.equipment}`.toLowerCase().includes(q)));},[query,muscleFilter]);
  const itemDone=(item:BuilderItem)=>item.exercise.metric_type==='strength'?item.strengthSets.length>0&&item.strengthSets.every(s=>s.done):item.done;
  const allComplete=builder.length>0&&builder.every(itemDone);

  useEffect(()=>{const load=async()=>{const {data:session}=await supabase.from('workout_sessions').select('id').eq('user_id',profile.id).eq('completed',true).order('ended_at',{ascending:false}).limit(1).maybeSingle();if(!session?.id)return;const {data:sets}=await supabase.from('workout_sets').select('exercise_name,set_number,weight_kg,reps,distance_km,duration_min').eq('session_id',session.id).order('created_at',{ascending:true});if(!sets?.length)return;const map=new Map<string,any[]>();for(const row of sets){const a=map.get(row.exercise_name)??[];a.push(row);map.set(row.exercise_name,a);}const template:BuilderItem[]=[];for(const [name,rows] of map.entries()){const ex=exerciseLibrary.find(x=>x.name===name);if(!ex)continue;template.push({id:`${ex.slug}-${makeId()}`,exercise:ex,strengthSets:ex.metric_type==='strength'?rows.map(r=>({id:makeId(),weight:r.weight_kg==null?'':String(r.weight_kg),reps:r.reps==null?'':String(r.reps),done:false})):[],distance:rows[0]?.distance_km==null?'':String(rows[0].distance_km),duration:rows[0]?.duration_min==null?'':String(rows[0].duration_min),load:rows[0]?.weight_kg==null?'':String(rows[0].weight_kg),done:false});}setLastWorkout(template);};load();},[profile.id]);
  useEffect(()=>{if(screen!=='active'||!activeStartedAt)return;const id=setInterval(()=>setElapsed(Math.floor((Date.now()-activeStartedAt)/1000)),1000);return()=>clearInterval(id);},[screen,activeStartedAt]);
  useEffect(()=>{if(restSeconds<=0)return;const id=setInterval(()=>setRestSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(id);},[restSeconds]);

  const getItem=(ex:LibraryExercise|null)=>ex?builder.find(x=>x.exercise.slug===ex.slug):undefined;
  const addExercise=async(ex:LibraryExercise)=>{
    let item=builder.find(x=>x.exercise.slug===ex.slug);if(!item){item=makeItem(ex);if(ex.metric_type==='strength'){const {data}=await supabase.from('workout_sets').select('weight_kg,reps,created_at').eq('user_id',profile.id).eq('exercise_name',ex.name).not('weight_kg','is',null).order('created_at',{ascending:false}).limit(2);if(data?.length)item.suggestion=(profile.age??18)<18?'Focus on consistent technique and age-appropriate coaching rather than automatically increasing load.':progressionSuggestion([...data].reverse().map((x:any)=>({weight_kg:Number(x.weight_kg),reps:Number(x.reps)})),ex.rep_min??8,ex.rep_max??12);}setBuilder(prev=>[...prev,item!]);}setDetailExercise(ex);setDetailTab('sets');setScreen('detail');
  };
  const removeExercise=(slug:string)=>setBuilder(p=>p.filter(x=>x.exercise.slug!==slug));
  const updateItem=(id:string,patch:Partial<BuilderItem>)=>setBuilder(p=>p.map(x=>x.id===id?{...x,...patch}:x));
  const updateSet=(itemId:string,setId:string,patch:Partial<StrengthSet>)=>setBuilder(p=>p.map(x=>x.id===itemId?{...x,strengthSets:x.strengthSets.map(s=>s.id===setId?{...s,...patch}:s)}:x));
  const addSet=(itemId:string)=>setBuilder(p=>p.map(x=>x.id===itemId?{...x,strengthSets:[...x.strengthSets,{id:makeId(),weight:x.strengthSets.at(-1)?.weight??'',reps:x.strengthSets.at(-1)?.reps??'10',done:false}]}:x));
  const removeSet=(itemId:string,setId:string)=>setBuilder(p=>p.map(x=>x.id===itemId&&x.strengthSets.length>1?{...x,strengthSets:x.strengthSets.filter(s=>s.id!==setId)}:x));
  const repeatLast=()=>setBuilder(lastWorkout.map(x=>({...x,id:`${x.exercise.slug}-${makeId()}`,done:false,strengthSets:x.strengthSets.map(s=>({...s,id:makeId(),done:false}))})));

  const validate=()=>{if(!builder.length){Alert.alert('Add exercises','Choose at least one exercise first.');return false;}for(const item of builder){if(item.exercise.metric_type==='strength'){for(const s of item.strengthSets)if(!s.reps||Number(s.reps)<=0){Alert.alert('Check reps',`Enter reps for ${item.exercise.name}.`);return false;}}else if(item.exercise.metric_type==='distance'&&!item.distance&&!item.duration){Alert.alert('Add distance or time',`Enter a distance or duration for ${item.exercise.name}.`);return false;}else if(item.exercise.metric_type==='time'&&!item.duration){Alert.alert('Add duration',`Enter a duration for ${item.exercise.name}.`);return false;}}return true;};
  const startWorkout=()=>{if(!validate())return;setBuilder(p=>p.map(x=>({...x,done:false,strengthSets:x.strengthSets.map(s=>({...s,done:false}))})));setActiveExerciseIndex(0);setElapsed(0);setRestSeconds(0);setActiveStartedAt(Date.now());setScreen('active');};
  const toggleSet=(item:BuilderItem,set:StrengthSet)=>{if(!set.done&&(!set.reps||Number(set.reps)<=0))return Alert.alert('Enter reps','Add the reps for this set before marking it complete.');updateSet(item.id,set.id,{done:!set.done});if(!set.done)setRestSeconds(90);};
  const completeCardio=(item:BuilderItem)=>{if(item.exercise.metric_type==='distance'&&!item.distance&&!item.duration)return Alert.alert('Add distance or time','Enter what you completed first.');if(item.exercise.metric_type==='time'&&!item.duration)return Alert.alert('Add duration','Enter what you completed first.');updateItem(item.id,{done:!item.done});if(!item.done)setRestSeconds(90);};
  const nextIncomplete=()=>{if(!builder.length)return;for(let offset=1;offset<=builder.length;offset++){const idx=(activeExerciseIndex+offset)%builder.length;if(!itemDone(builder[idx])){setActiveExerciseIndex(idx);return;}}};

  const saveWorkout=async()=>{if(!allComplete)return Alert.alert('Workout still in progress','Complete every exercise before finishing the workout.');setBusy(true);try{const summary=builder.map(x=>x.exercise.name).join(', ');const {data:session,error}=await supabase.from('workout_sessions').insert({user_id:profile.id,completed:true,started_at:new Date(activeStartedAt??Date.now()).toISOString(),ended_at:new Date().toISOString(),summary}).select('id').single();if(error)throw error;const rows:any[]=[];builder.forEach(item=>{if(item.exercise.metric_type==='strength')item.strengthSets.forEach((s,i)=>rows.push({session_id:session.id,user_id:profile.id,exercise_id:null,exercise_name:item.exercise.name,set_number:i+1,weight_kg:s.weight===''?0:Number(s.weight),reps:Number(s.reps),distance_km:null,duration_min:null}));else rows.push({session_id:session.id,user_id:profile.id,exercise_id:null,exercise_name:item.exercise.name,set_number:1,weight_kg:item.load?Number(item.load):null,reps:null,distance_km:item.distance?Number(item.distance):null,duration_min:item.duration?Number(item.duration):null});});const {error:setError}=await supabase.from('workout_sets').insert(rows);if(setError)throw setError;await supabase.from('workout_posts').insert({user_id:profile.id,session_id:session.id,summary});await recordWorkoutDay(profile.id);await supabase.rpc('apply_workout_to_challenges',{p_session_id:session.id});setLastWorkout(builder.map(x=>({...x,done:false,strengthSets:x.strengthSets.map(s=>({...s,done:false}))})));setBuilder([]);setScreen('browse');setActiveStartedAt(null);setElapsed(0);setRestSeconds(0);onProfileChanged();Alert.alert('Workout complete','Saved to your history and shared as a workout post with accepted friends.');}catch(e:any){Alert.alert('Could not save workout',e?.message??'Please try again.');}finally{setBusy(false);}};

  if(screen==='detail'&&detailExercise){const item=getItem(detailExercise);const img=detailExercise.visualKey?figureImages[detailExercise.visualKey]:undefined;return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled">
    <View style={styles.detailHeader}><Pressable onPress={()=>setScreen('browse')}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.detailTitle}>{detailExercise.name}</Text><Text style={styles.more}>•••</Text></View>
    <View style={styles.detailHero}>{img?<Image source={img} style={styles.detailFigure}/>:<View style={styles.cardioVisual}><Text style={styles.cardioEmoji}>{detailExercise.icon_emoji||'●'}</Text></View>}<View style={styles.muscleBox}><Text style={styles.muscleBoxTitle}>Primary Muscles</Text><Text style={styles.muscleLine}>• {detailExercise.targetArea}</Text><Text style={styles.muscleLine}>• {detailExercise.subsection}</Text><Text style={styles.muscleLine}>• {summarizeTargets(detailExercise)}</Text></View></View>
    <View style={styles.tabs}><Pressable onPress={()=>setDetailTab('sets')} style={[styles.tab,detailTab==='sets'&&styles.tabActive]}><Text style={[styles.tabText,detailTab==='sets'&&styles.tabTextActive]}>SETS</Text></Pressable><Pressable onPress={()=>setDetailTab('about')} style={[styles.tab,detailTab==='about'&&styles.tabActive]}><Text style={[styles.tabText,detailTab==='about'&&styles.tabTextActive]}>ABOUT</Text></Pressable></View>
    {detailTab==='about'?<Card><Text style={styles.aboutLabel}>Target</Text><Text style={styles.aboutText}>{detailExercise.targetArea} • {detailExercise.subsection}</Text><Text style={styles.aboutLabel}>Equipment</Text><Text style={styles.aboutText}>{detailExercise.equipment}</Text><Text style={styles.aboutLabel}>Recording</Text><Text style={styles.aboutText}>{detailExercise.metric_type==='strength'?'Sets, weight and reps':detailExercise.metric_type==='distance'?'Distance and/or duration':'Duration'}</Text></Card>:item?<Card>{item.suggestion?<View style={styles.suggest}><Text style={styles.suggestTitle}>TRAINING NOTE</Text><Text style={styles.suggestText}>{item.suggestion}</Text></View>:null}{item.exercise.metric_type==='strength'?<><SetTable item={item} active={false} onSet={(sid,patch)=>updateSet(item.id,sid,patch)} onToggle={()=>{}} onRemove={sid=>removeSet(item.id,sid)}/><Button title="＋ ADD SET" onPress={()=>addSet(item.id)}/></>:<CardioInputs item={item} onChange={patch=>updateItem(item.id,patch)}/>}<View style={styles.detailActions}><OutlineButton title="+ ADD ANOTHER EXERCISE" onPress={()=>setScreen('browse')}/><Button title="START WORKOUT" onPress={startWorkout}/></View><Pressable onPress={()=>{removeExercise(item.exercise.slug);setScreen('browse');}} style={styles.removeExercise}><Text style={styles.removeExerciseText}>Remove from workout</Text></Pressable></Card>:null}
  </ScrollView></KeyboardAvoidingView>;}

  if(screen==='active'){const current=builder[activeExerciseIndex];const img=current?.exercise.visualKey?figureImages[current.exercise.visualKey]:undefined;return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.activeWrap} keyboardShouldPersistTaps="handled">
    <View style={styles.activeHeader}><Pressable onPress={()=>Alert.alert('Leave workout?','Your current workout has not been saved yet.',[{text:'Keep training',style:'cancel'},{text:'Leave',style:'destructive',onPress:()=>setScreen('browse')}])}><Text style={styles.exit}>‹ Exit</Text></Pressable><Text style={styles.activeTitle}>Workout</Text><Text style={styles.more}>•••</Text></View>
    <Text style={styles.timer}>{formatTime(elapsed)}</Text><Text style={styles.timerLabel}>Workout Time</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.activeExercises}>{builder.map((item,i)=>{const done=itemDone(item);return <Pressable key={item.id} onPress={()=>setActiveExerciseIndex(i)} style={[styles.activeExerciseChip,i===activeExerciseIndex&&styles.activeExerciseSelected,done&&styles.activeExerciseDone]}><Text style={[styles.activeExerciseName,done&&{opacity:.45}]} numberOfLines={1}>{item.exercise.name}</Text><Text style={[styles.activeExerciseState,done&&{color:colors.green}]}>{done?'✓ Complete':i===activeExerciseIndex?'Current':'Pending'}</Text></Pressable>;})}</ScrollView>
    {current?<Card style={[styles.liveCard,itemDone(current)&&{opacity:.55}]}><View style={styles.liveHero}>{img?<Image source={img} style={styles.liveFigure}/>:<View style={styles.liveIconBox}><Text style={styles.liveEmoji}>{current.exercise.icon_emoji||'●'}</Text></View>}<View style={styles.liveMuscles}><Text style={styles.liveName}>{current.exercise.name}</Text><Text style={styles.primaryLabel}>PRIMARY MUSCLES</Text><Text style={styles.liveMeta}>{current.exercise.targetArea}</Text><Text style={styles.liveMeta}>{current.exercise.subsection}</Text></View></View>
      {current.exercise.metric_type==='strength'?<><SetTable item={current} active onSet={(sid,patch)=>updateSet(current.id,sid,patch)} onToggle={sid=>{const set=current.strengthSets.find(x=>x.id===sid);if(set)toggleSet(current,set);}} onRemove={sid=>removeSet(current.id,sid)}/><Button title="＋ ADD SET" onPress={()=>addSet(current.id)}/></>:<><CardioInputs item={current} onChange={patch=>updateItem(current.id,patch)}/><Button title={current.done?'MARK INCOMPLETE':'COMPLETE EXERCISE  ✓'} onPress={()=>completeCardio(current)} secondary={current.done}/></>}
    </Card>:null}
    {restSeconds>0?<View style={styles.restBanner}><View><Text style={styles.restLabel}>REST TIMER</Text><Text style={styles.restTime}>{formatTime(restSeconds)}</Text></View><Pressable onPress={()=>setRestSeconds(0)} style={styles.skip}><Text style={styles.skipText}>Skip rest</Text></Pressable></View>:null}
    {!allComplete?<OutlineButton title="NEXT UNFINISHED EXERCISE" onPress={nextIncomplete}/>:null}<Button title={busy?'SAVING…':allComplete?'FINISH WORKOUT  ✓':'FINISH WORKOUT'} onPress={saveWorkout} disabled={busy||!allComplete}/>
  </ScrollView></KeyboardAvoidingView>;}

  return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled">
    <View style={styles.browseHeader}><View><Text style={styles.browseTitle}>New Workout</Text><Text style={styles.browseSub}>{builder.length?`${builder.length} exercise${builder.length===1?'':'s'} ready`:'Choose an exercise to set it up'}</Text></View><Text style={styles.stopwatch}>◷</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.muscleScroller}><Pressable onPress={()=>setMuscleFilter('All')} style={styles.muscleChoice}><View style={[styles.circle,muscleFilter==='All'&&styles.circleActive]}><Image source={require('../../../assets/nav/workout.png')} style={[styles.circleIcon,{tintColor:muscleFilter==='All'?colors.primary:colors.muted}]}/></View><Text style={[styles.choiceLabel,muscleFilter==='All'&&styles.choiceLabelActive]}>All</Text></Pressable>{muscleCards.map(m=><Pressable key={m.label} onPress={()=>setMuscleFilter(m.label as any)} style={styles.muscleChoice}><View style={[styles.circle,muscleFilter===m.label&&styles.circleActive]}><Image source={m.image} style={styles.circleAnatomy}/></View><Text style={[styles.choiceLabel,muscleFilter===m.label&&styles.choiceLabelActive]}>{m.label}</Text></Pressable>)}</ScrollView>
    <Input value={query} onChangeText={setQuery} placeholder="Search exercises…"/>
    {builder.length?<Card style={styles.selectedCard}><View style={{flex:1}}><Text style={styles.selectedTitle}>{builder.length} exercise{builder.length===1?'':'s'} configured</Text><Text style={styles.selectedMeta}>Add another or start when you are ready.</Text></View><Pressable onPress={startWorkout} style={styles.startSmall}><Text style={styles.startSmallText}>START</Text></Pressable></Card>:null}
    {lastWorkout.length?<Pressable onPress={repeatLast} style={styles.repeat}><Text style={styles.repeatText}>↻ Repeat last workout</Text></Pressable>:null}
    <View style={styles.exerciseList}>{filtered.map(ex=>{const img=ex.visualKey?figureImages[ex.visualKey]:undefined;const selected=builder.some(x=>x.exercise.slug===ex.slug);return <Pressable key={ex.slug} onPress={()=>addExercise(ex)} style={styles.exerciseRow}>{img?<Image source={img} style={styles.thumb}/>:<View style={styles.blankThumb}><Text style={styles.listEmoji}>{ex.icon_emoji||'●'}</Text></View>}<View style={{flex:1}}><Text style={styles.target}>{ex.targetArea}</Text><Text style={styles.exName}>{ex.name}</Text><Text style={styles.exMeta}>{ex.equipment} • {ex.metric_type==='strength'?'sets / reps / weight':ex.metric_type==='distance'?'distance / duration':'duration'}</Text></View><View style={[styles.plus,selected&&styles.plusSelected]}><Text style={[styles.plusText,{color:selected?'#fff':colors.primary}]}>{selected?'✓':'+'}</Text></View></Pressable>;})}</View>
  </ScrollView></KeyboardAvoidingView>;
}

function SetTable({item,active,onSet,onToggle,onRemove}:{item:BuilderItem;active:boolean;onSet:(setId:string,patch:Partial<StrengthSet>)=>void;onToggle:(setId:string)=>void;onRemove:(setId:string)=>void}){const {colors}=useTheme();const s=createStyles(colors);return <View><View style={s.tableHead}><Text style={s.setCol}>SET</Text><Text style={s.flexCol}>WEIGHT (kg)</Text><Text style={s.flexCol}>REPS</Text><Text style={s.checkCol}>✓</Text></View>{item.strengthSets.map((set,i)=><View key={set.id} style={[s.tableRow,set.done&&{opacity:.48}]}><Text style={s.setCol}>{i+1}</Text><Input style={s.tableInput} value={set.weight} onChangeText={v=>onSet(set.id,{weight:v})} keyboardType="decimal-pad" placeholder="0"/><Input style={[s.tableInput,set.done&&{color:colors.green}]} value={set.reps} onChangeText={v=>onSet(set.id,{reps:v})} keyboardType="number-pad" placeholder="10"/>{active?<Pressable onPress={()=>onToggle(set.id)} style={[s.check,set.done&&s.checkDone]}><Text style={[s.checkText,set.done&&{color:colors.green}]}>{set.done?'✓':'○'}</Text></Pressable>:<Pressable onPress={()=>onRemove(set.id)} style={s.check}><Text style={s.remove}>−</Text></Pressable>}</View>)}</View>;}
function CardioInputs({item,onChange}:{item:BuilderItem;onChange:(patch:Partial<BuilderItem>)=>void}){const {colors}=useTheme();const s=createStyles(colors);return <View><Text style={s.cardioHint}>Record the fields that best match this exercise.</Text>{item.exercise.allowsLoad?<Input value={item.load} onChangeText={v=>onChange({load:v})} keyboardType="decimal-pad" placeholder="Load (kg), if used"/>:null}<View style={s.two}>{item.exercise.metric_type==='distance'?<Input style={{flex:1}} value={item.distance} onChangeText={v=>onChange({distance:v})} keyboardType="decimal-pad" placeholder="Distance (km)"/>:null}<Input style={{flex:1}} value={item.duration} onChangeText={v=>onChange({duration:v})} keyboardType="decimal-pad" placeholder="Duration (min)"/></View></View>;}

const createStyles=(colors:any)=>StyleSheet.create({
  wrap:{padding:16,paddingTop:10,paddingBottom:34},browseHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},browseTitle:{color:colors.text,fontSize:24,fontWeight:'900'},browseSub:{color:colors.muted,fontSize:11,marginTop:2},stopwatch:{color:colors.text,fontSize:24},muscleScroller:{gap:10,paddingBottom:14},muscleChoice:{alignItems:'center',width:58},circle:{width:48,height:48,borderRadius:24,borderWidth:1,borderColor:colors.border,backgroundColor:colors.panel,alignItems:'center',justifyContent:'center',overflow:'hidden'},circleActive:{borderColor:colors.primary},circleIcon:{width:22,height:22,resizeMode:'contain'},circleAnatomy:{width:46,height:46,resizeMode:'contain'},choiceLabel:{color:colors.muted,fontSize:9,marginTop:5},choiceLabelActive:{color:colors.primary,fontWeight:'900'},selectedCard:{flexDirection:'row',alignItems:'center',gap:10,padding:12},selectedTitle:{color:colors.text,fontWeight:'900'},selectedMeta:{color:colors.muted,fontSize:10,marginTop:3},startSmall:{backgroundColor:colors.primary,borderRadius:8,paddingHorizontal:14,paddingVertical:10},startSmallText:{color:'#fff',fontWeight:'900',fontSize:11},repeat:{alignSelf:'flex-start',paddingVertical:8},repeatText:{color:colors.blue,fontWeight:'800',fontSize:11},exerciseList:{gap:7},exerciseRow:{minHeight:78,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:9},thumb:{width:58,height:58,resizeMode:'contain'},blankThumb:{width:58,height:58,alignItems:'center',justifyContent:'center',backgroundColor:colors.panel2,borderRadius:10},listEmoji:{fontSize:26},target:{color:colors.primary,fontWeight:'900',fontSize:10},exName:{color:colors.text,fontWeight:'900',fontSize:14,marginTop:1},exMeta:{color:colors.muted,fontSize:10,marginTop:3},plus:{width:30,height:30,borderRadius:15,borderWidth:1.5,borderColor:colors.primary,alignItems:'center',justifyContent:'center'},plusSelected:{backgroundColor:colors.green,borderColor:colors.green},plusText:{fontWeight:'900',fontSize:20,lineHeight:22},
  detailHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:9},back:{color:colors.text,fontSize:36,fontWeight:'300'},detailTitle:{color:colors.text,fontSize:19,fontWeight:'900',maxWidth:'75%',textAlign:'center'},more:{color:colors.text,fontSize:16,fontWeight:'900'},detailHero:{flexDirection:'row',minHeight:250,alignItems:'center'},detailFigure:{flex:1,height:250,resizeMode:'contain'},cardioVisual:{flex:1,height:220,alignItems:'center',justifyContent:'center'},cardioEmoji:{fontSize:92},muscleBox:{width:145,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:11},muscleBoxTitle:{color:colors.text,fontWeight:'900',fontSize:12,marginBottom:7},muscleLine:{color:colors.muted,fontSize:10,lineHeight:17},tabs:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:colors.border,marginBottom:12},tab:{flex:1,alignItems:'center',paddingVertical:11},tabActive:{borderBottomWidth:2,borderBottomColor:colors.primary},tabText:{color:colors.muted,fontWeight:'800',fontSize:11},tabTextActive:{color:colors.primary},aboutLabel:{color:colors.muted,fontSize:10,fontWeight:'900',marginTop:7},aboutText:{color:colors.text,fontSize:14,fontWeight:'700',marginTop:2},suggest:{backgroundColor:colors.blueSoft,borderRadius:10,padding:10,marginBottom:10},suggestTitle:{color:colors.blue,fontWeight:'900',fontSize:9},suggestText:{color:colors.text,fontSize:11,marginTop:3,lineHeight:16},detailActions:{marginTop:12},removeExercise:{alignItems:'center',padding:10},removeExerciseText:{color:colors.muted,fontSize:11,fontWeight:'800'},
  tableHead:{flexDirection:'row',alignItems:'center',gap:7,paddingVertical:7,borderBottomWidth:1,borderBottomColor:colors.border},tableRow:{flexDirection:'row',alignItems:'center',gap:7,paddingVertical:5,borderBottomWidth:1,borderBottomColor:colors.border},setCol:{width:34,color:colors.text,fontWeight:'800',fontSize:11,textAlign:'center'},flexCol:{flex:1,color:colors.muted,fontWeight:'900',fontSize:9,textAlign:'center'},checkCol:{width:34,color:colors.muted,textAlign:'center',fontWeight:'900'},tableInput:{flex:1,marginBottom:0,minHeight:38,textAlign:'center'},check:{width:34,height:34,alignItems:'center',justifyContent:'center'},checkDone:{borderRadius:17},checkText:{color:colors.muted,fontSize:22,fontWeight:'900'},remove:{color:colors.muted,fontSize:22},two:{flexDirection:'row',gap:8},cardioHint:{color:colors.muted,fontSize:11,marginBottom:9},
  activeWrap:{padding:16,paddingTop:10,paddingBottom:34},activeHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},exit:{color:colors.text,fontSize:14},activeTitle:{color:colors.text,fontWeight:'900',fontSize:18},timer:{color:colors.text,fontSize:43,fontWeight:'800',textAlign:'center',marginTop:14},timerLabel:{color:colors.muted,textAlign:'center',fontSize:11,marginBottom:13},activeExercises:{gap:7,paddingBottom:12},activeExerciseChip:{width:128,borderWidth:1,borderColor:colors.border,borderRadius:11,backgroundColor:colors.panel,padding:9},activeExerciseSelected:{borderColor:colors.primary},activeExerciseDone:{backgroundColor:colors.panel2},activeExerciseName:{color:colors.text,fontWeight:'900',fontSize:11},activeExerciseState:{color:colors.muted,fontSize:8,marginTop:4,fontWeight:'800'},liveCard:{padding:13},liveHero:{flexDirection:'row',alignItems:'center',minHeight:150,borderBottomWidth:1,borderBottomColor:colors.border,marginBottom:8},liveFigure:{width:135,height:155,resizeMode:'contain'},liveIconBox:{width:135,height:150,alignItems:'center',justifyContent:'center'},liveEmoji:{fontSize:66},liveMuscles:{flex:1,paddingLeft:9},liveName:{color:colors.text,fontSize:18,fontWeight:'900',marginBottom:10},primaryLabel:{color:colors.primary,fontSize:9,fontWeight:'900'},liveMeta:{color:colors.muted,fontSize:11,marginTop:4},restBanner:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:colors.blueSoft,borderRadius:13,padding:12,marginBottom:8},restLabel:{color:colors.blue,fontSize:9,fontWeight:'900'},restTime:{color:colors.text,fontSize:25,fontWeight:'900',marginTop:2},skip:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.blue,borderRadius:10,paddingHorizontal:12,paddingVertical:8},skipText:{color:colors.blue,fontWeight:'900',fontSize:11}
});
