import React,{useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,View}from'react-native';
import{Button,Card,Input,OutlineButton,SectionTitle,useTheme}from'../components/UI';
import{Profile}from'../lib/types';import{supabase}from'../lib/supabase';
const key=(d:Date)=>d.toISOString().slice(0,10);
export default function NutritionLibraryScreen({profile,onBack}:{profile:Profile;onBack:()=>void}){
 const{colors}=useTheme(),s=StyleSheet.create({wrap:{padding:16,gap:10},title:{color:colors.text,fontSize:27,fontWeight:'900'},row:{paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},text:{color:colors.text,fontWeight:'800'},muted:{color:colors.muted,fontSize:11}});
 const[name,setName]=useState(''),[recipe,setRecipe]=useState(''),[water,setWater]=useState('250'),[meals,setMeals]=useState<any[]>([]),[recipes,setRecipes]=useState<any[]>([]),[today,setToday]=useState<any[]>([]);
 const load=async()=>{const start=key(new Date());const[a,b,c]=await Promise.all([supabase.from('saved_meals').select('*').eq('user_id',profile.id).order('created_at',{ascending:false}),supabase.from('recipes').select('*').eq('user_id',profile.id).order('created_at',{ascending:false}),supabase.from('food_logs').select('*').eq('user_id',profile.id).gte('logged_at',start+'T00:00:00')]);setMeals(a.data??[]);setRecipes(b.data??[]);setToday(c.data??[])};
 useEffect(()=>{load()},[profile.id]);
 const saveMeal=async()=>{if(!name.trim()||!today.length)return Alert.alert('Saved meal','Enter a name and log at least one food today.');const{data,error}=await supabase.from('saved_meals').insert({user_id:profile.id,name:name.trim(),meal_type:'custom'}).select().single();if(error)return Alert.alert('Saved meal',error.message);const items=today.map(x=>({meal_id:data.id,food_name:x.food_name,serving:x.serving,servings:x.servings,calories:x.calories,protein_g:x.protein_g,carbs_g:x.carbs_g,fat_g:x.fat_g,fibre_g:x.fibre_g??0,provider_food_id:x.provider_food_id,serving_id:x.serving_id}));await supabase.from('saved_meal_items').insert(items);setName('');load()};
 const saveRecipe=async()=>{if(!recipe.trim()||!today.length)return Alert.alert('Recipe','Enter a recipe name and log its ingredients first.');const{data,error}=await supabase.from('recipes').insert({user_id:profile.id,name:recipe.trim(),servings:1}).select().single();if(error)return Alert.alert('Recipe',error.message);await supabase.from('recipe_items').insert(today.map(x=>({recipe_id:data.id,food_name:x.food_name,serving:x.serving,quantity:x.servings,calories:x.calories,protein_g:x.protein_g,carbs_g:x.carbs_g,fat_g:x.fat_g,fibre_g:x.fibre_g??0,provider_food_id:x.provider_food_id,serving_id:x.serving_id})));setRecipe('');load()};
 const copyYesterday=async()=>{const d=new Date();d.setDate(d.getDate()-1);const from=key(d);const{data}=await supabase.from('food_logs').select('*').eq('user_id',profile.id).gte('logged_at',from+'T00:00:00').lt('logged_at',key(new Date())+'T00:00:00');if(!data?.length)return Alert.alert('Copy yesterday','No foods were logged yesterday.');const rows=data.map(({id,logged_at,created_at,...x}:any)=>({...x,logged_at:new Date().toISOString(),client_request_id:null}));const{error}=await supabase.from('food_logs').insert(rows);Alert.alert('Copy yesterday',error?error.message:'Yesterday’s meals were copied to today.')};
 const addWater=async()=>{const amount=Number(water);if(!amount||amount<1||amount>5000)return;const{error}=await supabase.from('water_logs').insert({user_id:profile.id,amount_ml:amount});if(error)Alert.alert('Water',error.message);else Alert.alert('Water',amount+' ml added.')};
 return <ScrollView contentContainerStyle={s.wrap}><OutlineButton title="‹ Food diary" onPress={onBack}/><Text style={s.title}>Meals, recipes & water</Text><Card><SectionTitle title="Copy previous meals" subtitle="Copies yesterday into today; you can edit the new entries."/><Button title="Copy yesterday" onPress={copyYesterday}/></Card><Card><SectionTitle title="Save today as a meal"/><Input value={name} onChangeText={setName} placeholder="Meal name"/><Button title="Save meal" onPress={saveMeal}/>{meals.map(x=><View key={x.id} style={s.row}><Text style={s.text}>{x.name}</Text><Text style={s.muted}>Saved meal</Text></View>)}</Card><Card><SectionTitle title="Recipe builder" subtitle="Log ingredients in the diary, then save them as a reusable recipe."/><Input value={recipe} onChangeText={setRecipe} placeholder="Recipe name"/><Button title="Save recipe from today’s items" onPress={saveRecipe}/>{recipes.map(x=><View key={x.id} style={s.row}><Text style={s.text}>{x.name}</Text><Text style={s.muted}>{x.servings} serving(s)</Text></View>)}</Card><Card><SectionTitle title="Water"/><Input value={water} onChangeText={setWater} keyboardType="number-pad" placeholder="ml"/><Button title="Add water" onPress={addWater}/></Card><Card><SectionTitle title="Future assisted entry" subtitle="Photo and natural-language estimates must always be labelled Estimated nutrition and reviewed before anything is saved."/></Card></ScrollView>;
}
