import React,{useEffect,useState}from'react';
import{Alert,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{Button,Card,Input,OutlineButton,SectionTitle,useTheme}from'../components/UI';
import{Profile}from'../lib/types';import{supabase}from'../lib/supabase';
export default function SharedGymScreen({profile,onBack}:{profile:Profile;onBack:()=>void}){
 const{colors}=useTheme(),s=StyleSheet.create({wrap:{padding:16,gap:10},title:{color:colors.text,fontSize:27,fontWeight:'900'},row:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.border},text:{color:colors.text,fontWeight:'800'},muted:{color:colors.muted,fontSize:11,marginTop:3}});
 const[title,setTitle]=useState('Gym session'),[username,setUsername]=useState(''),[sessions,setSessions]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[people,setPeople]=useState<any[]>([]);
 const load=async()=>{const{data}=await supabase.from('shared_gym_sessions').select('*').order('created_at',{ascending:false});setSessions(data??[])};
 useEffect(()=>{load()},[profile.id]);
 const create=async()=>{const{data,error}=await supabase.from('shared_gym_sessions').insert({creator_id:profile.id,title:title.trim()||'Gym session',status:'invited'}).select().single();if(error)return Alert.alert('Gym session',error.message);await supabase.from('shared_gym_participants').insert({shared_session_id:data.id,user_id:profile.id,invite_status:'accepted',publish_consent:false});setSelected(data);open(data);load()};
 const open=async(x:any)=>{setSelected(x);const{data}=await supabase.from('shared_gym_participants').select('user_id,invite_status,publish_consent,completed_at').eq('shared_session_id',x.id);const ids=(data??[]).map((p:any)=>p.user_id);const{data:profiles}=ids.length?await supabase.from('profiles').select('id,username').in('id',ids):{data:[]};setPeople((data??[]).map((p:any)=>({...p,username:(profiles??[]).find((u:any)=>u.id===p.user_id)?.username??'Member'})))};
 const invite=async()=>{const{data:u}=await supabase.from('profiles').select('id').eq('username',username.trim().replace(/^@/,'')).maybeSingle();if(!u)return Alert.alert('Friend not found','Enter the exact FitHub username.');const{error}=await supabase.from('shared_gym_participants').insert({shared_session_id:selected.id,user_id:u.id,invite_status:'pending',publish_consent:false});if(error)Alert.alert('Invite',error.message);else{setUsername('');open(selected)}};
 const reply=async(status:'accepted'|'declined')=>{await supabase.from('shared_gym_participants').update({invite_status:status}).eq('shared_session_id',selected.id).eq('user_id',profile.id);open(selected)};
 const consent=async()=>{const mine=people.find(x=>x.user_id===profile.id);await supabase.from('shared_gym_participants').update({publish_consent:!mine?.publish_consent}).eq('shared_session_id',selected.id).eq('user_id',profile.id);open(selected)};
 const publish=async()=>{const blocked=people.some(x=>x.invite_status!=='accepted'||!x.publish_consent);if(blocked)return Alert.alert('Consent required','Every included participant must accept the session and approve the joint post first.');const{error}=await supabase.from('shared_workout_posts').insert({shared_session_id:selected.id,created_by:profile.id,caption:selected.title,published_at:new Date().toISOString()});Alert.alert('Joint post',error?error.message:'The shared completed-workout post was created.')};
 if(selected){const mine=people.find(x=>x.user_id===profile.id);return <ScrollView contentContainerStyle={s.wrap}><OutlineButton title="‹ Shared sessions" onPress={()=>setSelected(null)}/><Text style={s.title}>{selected.title}</Text>{mine?.invite_status==='pending'?<Card><SectionTitle title="Gym invitation"/><View style={{flexDirection:'row',gap:8}}><Button title="Accept" onPress={()=>reply('accepted')}/><Button title="Decline" onPress={()=>reply('declined')} secondary/></View></Card>:null}<Card><SectionTitle title="Invite friends" subtitle="Each person records their own workout."/><Input value={username} onChangeText={setUsername} placeholder="@username"/><Button title="Send gym invite" onPress={invite}/></Card><Card><SectionTitle title="Participants & publishing consent"/>{people.map(x=><View key={x.user_id} style={s.row}><Text style={s.text}>@{x.username}</Text><Text style={s.muted}>{x.invite_status} • {x.publish_consent?'post approved':'post not approved'}</Text></View>)}<OutlineButton title={mine?.publish_consent?'Withdraw my post consent':'Approve joint post'} onPress={consent}/><Button title="Create joint completed-workout post" onPress={publish}/><Text style={s.muted}>An optional group photo can be added only after participants approve publication.</Text></Card></ScrollView>;}
 return <ScrollView contentContainerStyle={s.wrap}><OutlineButton title="‹ Back" onPress={onBack}/><Text style={s.title}>Shared gym sessions</Text><Card><SectionTitle title="Plan with friends"/><Input value={title} onChangeText={setTitle}/><Button title="Create shared session" onPress={create}/></Card>{sessions.map(x=><Pressable key={x.id} onPress={()=>open(x)}><Card><Text style={s.text}>{x.title}</Text><Text style={s.muted}>Open invitation and consent ›</Text></Card></Pressable>)}</ScrollView>;
}
