import React,{useEffect,useState}from'react';
import{Alert,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{Button,Card,Input,OutlineButton,SectionTitle,useTheme}from'../components/UI';
import{Profile}from'../lib/types';import{supabase}from'../lib/supabase';
export default function StepGroupsScreen({profile,onBack}:{profile:Profile;onBack:()=>void}){
 const{colors}=useTheme(),s=StyleSheet.create({wrap:{padding:16,gap:10},title:{color:colors.text,fontSize:27,fontWeight:'900'},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},text:{color:colors.text,fontWeight:'800'},muted:{color:colors.muted,fontSize:11}});
 const[name,setName]=useState(''),[invite,setInvite]=useState(''),[groups,setGroups]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[board,setBoard]=useState<any[]>([]);
 const load=async()=>{const{data}=await supabase.from('step_groups').select('*').order('created_at',{ascending:false});setGroups(data??[])};
 useEffect(()=>{load()},[profile.id]);
 const create=async()=>{if(!name.trim())return;const{data,error}=await supabase.from('step_groups').insert({creator_id:profile.id,name:name.trim(),visibility:'private'}).select().single();if(error)return Alert.alert('Group',error.message);await supabase.from('step_group_members').insert({group_id:data.id,user_id:profile.id,invited_by:profile.id,status:'accepted',joined_at:new Date().toISOString()});setName('');load()};
 const open=async(g:any)=>{setSelected(g);const{data:m}=await supabase.from('step_group_members').select('user_id').eq('group_id',g.id).eq('status','accepted');const ids=(m??[]).map((x:any)=>x.user_id);if(!ids.length)return setBoard([]);const start=new Date();start.setDate(start.getDate()-6);const[{data:steps},{data:p}]=await Promise.all([supabase.from('daily_steps').select('user_id,steps,local_date').in('user_id',ids).gte('local_date',start.toISOString().slice(0,10)),supabase.from('profiles').select('id,username').in('id',ids)]);setBoard(ids.map((id:string)=>{const rows=(steps??[]).filter((x:any)=>x.user_id===id);return{id,name:(p??[]).find((x:any)=>x.id===id)?.username??'Member',total:rows.reduce((a:number,x:any)=>a+Number(x.steps),0),days:rows.filter((x:any)=>x.steps>0).length}}).sort((a:any,b:any)=>b.total-a.total))};
 const sendInvite=async()=>{const{data:u}=await supabase.from('profiles').select('id').eq('username',invite.trim().replace(/^@/,'')).maybeSingle();if(!u)return Alert.alert('Friend not found','Enter their exact FitHub username.');const{error}=await supabase.from('step_group_members').insert({group_id:selected.id,user_id:u.id,invited_by:profile.id,status:'pending'});if(error)Alert.alert('Invite',error.message);else{setInvite('');Alert.alert('Invite sent','They can accept from their step groups.')}};
 if(selected)return <ScrollView contentContainerStyle={s.wrap}><OutlineButton title="‹ Groups" onPress={()=>setSelected(null)}/><Text style={s.title}>{selected.name}</Text><Card><SectionTitle title="Invite a friend" subtitle="Only accepted members can see shared totals."/><Input value={invite} onChangeText={setInvite} placeholder="@username"/><Button title="Send invite" onPress={sendInvite}/></Card><Card><SectionTitle title="Weekly leaderboard" subtitle="Rank, total, daily average and active days." />{board.map((x:any,i)=><View style={s.row} key={x.id}><View><Text style={s.text}>{i+1}. @{x.name}</Text><Text style={s.muted}>{x.days} active days • {x.days?Math.round(x.total/x.days):0} daily average</Text></View><Text style={s.text}>{x.total.toLocaleString()}</Text></View>)}</Card></ScrollView>;
 return <ScrollView contentContainerStyle={s.wrap}><OutlineButton title="‹ Back" onPress={onBack}/><Text style={s.title}>Step groups</Text><Card><SectionTitle title="Create private group"/><Input value={name} onChangeText={setName} placeholder="Group name"/><Button title="Create group" onPress={create}/></Card>{groups.map(g=><Pressable key={g.id} onPress={()=>open(g)}><Card><Text style={s.text}>{g.name}</Text><Text style={s.muted}>Private leaderboard ›</Text></Card></Pressable>)}</ScrollView>;
}
